services:
  apache:
    image: php:8.2-apache
    restart: 'always'
    ports:
      - '80:80'
    volumes:
      - ./public_html:/var/www/html
      # - "./usr/local/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"
  mysql:
    container_name: db
    image: mysql:8.0
    restart: always
    volumes: 
      - ./var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    depends_on:
      - apache
  phpmyadmin:
    container_name: phpmyadmin
    image: arm64v8/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOSTS=mysql
    ports:
      - "3000:80"