services:
  apache:
    container_name: apache
    build : .
    restart: 'always'
    ports:
      - '80:80'
    volumes:
      - ./public_html:/var/www/html
      - ./etc/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./private/var/log/apache2/:/private/var/log/apache2
  experiment:
    container_name: exp
    image: php:8.3-apache
  mysql:
    container_name: db
    image: mysql:8.0
    restart: always
    volumes: 
      - ./var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    depends_on:
      - apache
  phpmyadmin:
    container_name: phpmyadmin
    image: arm64v8/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOSTS=mysql
    ports:
      - "3000:80"